name: Testing fastpm with overdensity field 
on: [push]
jobs:
  test-fastpm-on-image:
    runs-on: ubuntu-latest
    container: maurorigo/ldlimg:final

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run test fastpm
        run: |
          . /opt/miniconda3/etc/profile.d/conda.sh
          conda activate LDLenv
          cd docker
          python testfastpm.py 0
          python ../genimage/pylians_genimage_fastpm.py FastPM_Nmesh64_Nstep10_z0.00
          rm -r FastPM_Nmesh64_Nstep10_z0.00
