name: Testing fastpm 
on: [push]
jobs:
  test-fastpm-on-image:
    runs-on: ubuntu-latest
    container: maurorigo/ldlimg:focal

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run test fastpm
        run: |
          . /root/miniconda3/etc/profile.d/conda.sh
          conda activate LDLenv
          cd Docker
          python testfastpm.py 0
